# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Create env file
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: |
          touch .env
          echo DB_HOST: ${{secrets.DB_HOST}} >> .env
          echo DB_PASS: ${{secrets.DB_PASS}} >> .env
          echo DB_ADMIN: ${{secrets.DB_ADMIN}} >> .env
          echo DB_PASS: ${{secrets.DB_PASS}} >> .env
          echo DB_SECRET: ${{secrets.DB_SECRET}} >> .env
          echo EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}} >> .env
          echo EMAIL: ${{secrets.EMAIL}} >> .env
          echo EMAIL_MAIL_URL: ${{secrets.EMAIL_MAIL_URL}} >> .env
          cat .env
    - run: pm2 restart ModMenus_back-end 
